the appearance of the personal account has been realized
baza-trainee/mich-team pull request #62
Opened 2024-02-14 19:06 UTC by AndriiBeznosov

Implemented the appearance of the personal account without interaction with the backend

2024-02-14 21:20 UTC, moskalenko-mm requested changes
1. прибери package-lock.json
2. що за нова бібліотека "framer-motion"?
3. навіщо ці зміни в хедері?

2024-02-14 23:02 UTC, AndriiBeznosov commented
> 1. прибери package-lock.json
> 2. що за нова бібліотека "framer-motion"?
> 3. навіщо ці зміни в хедері?

1 - можеш, будь ласка, пояснити чому прибрати  package-lock.json (в особисті напиши)?
2 - framer-motion - бібліотека для плавного відкривання компонентів, зроблено універсальний контейнер ComponentAnimate, який анімує по налаштуванню
3 - це єдиний перехід в особистий кабінет, прибрати ?

2024-02-15 07:20 UTC, moskalenko-mm commented
1. відповів
2. ок
3. залишай, я запитав для розуміння необхідності змін

2024-02-15 09:26 UTC, moskalenko-mm approved these changes

2024-02-15 09:26 UTC, merged